# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b81b2622fb0c27e414ba3d8d83666fbfa5a9920cced25eaea9772460acb6b68215cfa5ab5df6b6305ad3d42477ed158d18dda71092c2dda0eac7cc6fa21239c1

test:
  secret_key_base: e4e643d07d47d9526dff08ac91c139f3701cd144fc262b699b0e862c33550befe632c2ea2ab735e396dcce0ec3aa063fbf3d8c08035940925119831d30bcf191

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
